import haxe.io.Bytes;

import RoomProtocolTestCase.StubConnection;
import io.colyseus.Room;
import io.colyseus.RoomClock;
import io.colyseus.InputHandle;
import io.colyseus.serializer.schema.InputEncoder;

import schema.phase0.P0State;
import schema.input.MoveInput;

/** Clock stub with scripted readings for stamp framing tests. */
class StubClock extends RoomClock {
    public var serverNowValue: Float = 0;
    public var lastServerTimeValue: Float = 0;
    public var smoothedRttValue: Float = 0;

    override public function serverNow(): Float return serverNowValue;
    override public function lastServerTime(): Float return lastServerTimeValue;
    override public function smoothedRtt(): Float return smoothedRttValue;
}

/**
 * Phase 3 — input layer + RoomClock.
 *
 * Fixtures generated by colyseus-0.18 PORTING/generate-input-fixtures.cts
 * (self-verified against the JS schema InputEncoder/InputDecoder, the real
 * InputHandleImpl and RoomClockImpl). Contract:
 * PORTING/sdk-ports-input-layer.md.
 */
class InputTestCase extends haxe.unit.TestCase {

    private function getBytes(arr: Array<Int>): Bytes {
        var bytes = Bytes.alloc(arr.length);
        var i: Int = 0;
        for (byte in arr) { bytes.set(i++, byte); }
        return bytes;
    }

    private function assertBytes(expected: Array<Int>, actual: Bytes, ?pos: haxe.PosInfos) {
        var actualArr = [for (i in 0...actual.length) actual.get(i)];
        assertEquals(expected.join(","), actualArr.join(","), pos);
    }

    public function testInputEncoderReliable() {
        var input = new MoveInput();
        var enc = new InputEncoder(input);

        input.vx = 1.5; input.vy = -2; input.jump = true; input.action = 3;
        assertBytes([128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3], enc.encode());

        input.vx = 2.5;
        assertBytes([128, 202, 0, 0, 32, 64], enc.encode());

        // no change → empty body
        assertBytes([], enc.encode());

        input.jump = false; input.action = 7;
        assertBytes([130, 0, 131, 7], enc.encode());

        // reset → full snapshot of populated fields
        enc.reset();
        assertBytes([128, 202, 0, 0, 32, 64, 129, 254, 130, 0, 131, 7], enc.encode());
    }

    public function testInputEncoderUnreliable() {
        var input = new MoveInput();
        var enc = new InputEncoder(input, "unreliable", 3);

        input.vx = 1.5; input.vy = -2; input.jump = true; input.action = 3;
        assertBytes([1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3], enc.encode());
        assertEquals(1, enc.seq);

        input.vx = 2.5;
        assertBytes([1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64], enc.encode());

        // no change → carry-forward empty slot, ring re-emitted
        assertBytes([1, 12, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3, 6, 128, 202, 0, 0, 32, 64, 0], enc.encode());

        input.vy = 9;
        assertBytes([2, 6, 128, 202, 0, 0, 32, 64, 0, 2, 129, 9], enc.encode());
        assertEquals(4, enc.seq);
    }

    private function makeHandle(clock: RoomClock, ?mode: String, ?opts: { stampRender: Bool, stampReckon: Bool, ?renderDelay: Float, ?allowRewind: Dynamic -> Bool }): { handle: InputHandle<Dynamic>, stub: StubConnection } {
        var input = new MoveInput();
        var enc = new InputEncoder(input, mode, 3);
        var stub = new StubConnection();
        var o = (opts != null) ? opts : { stampRender: false, stampReckon: false };
        var handle = @:privateAccess new InputHandle(input, enc, {
            stampRender: o.stampRender,
            stampReckon: o.stampReckon,
            renderDelay: o.renderDelay,
            allowRewind: o.allowRewind,
        }, () -> (stub : io.colyseus.Connection), () -> clock);
        return { handle: handle, stub: stub };
    }

    public function testHandleReliableNoStamp() {
        var r = makeHandle(new StubClock());
        var input: MoveInput = cast r.handle.data;

        input.vx = 1.5; input.vy = -2; input.jump = true; input.action = 3;
        assertEquals(1, r.handle.send());
        input.vx = 2.5;
        assertEquals(2, r.handle.send());
        assertEquals(3, r.handle.send()); // no change → body-less [19]

        assertEquals(3, r.handle.sentCount);
        assertBytes([19, 128, 202, 0, 0, 192, 63, 129, 254, 130, 1, 131, 3], r.stub.sent[0]);
        assertBytes([19, 128, 202, 0, 0, 32, 64], r.stub.sent[1]);
        assertBytes([19], r.stub.sent[2]);
    }

    public function testHandleReliableStampedBoth() {
        var clock = new StubClock();
        clock.lastServerTimeValue = 500; // synced
        clock.smoothedRttValue = 80;
        var r = makeHandle(clock, { stampRender: true, stampReckon: true, renderDelay: 50 });
        var input: MoveInput = cast r.handle.data;

        clock.serverNowValue = 1000;
        input.vx = 1.5;
        r.handle.send();
        clock.serverNowValue = 1016.7;
        input.vx = 2;
        r.handle.send();
        clock.serverNowValue = 1033.4;
        r.handle.send();

        // [19|0x80][varint Δreckon][uint16 renderDelta=90][delta body]
        assertBytes([147, 205, 232, 3, 90, 0, 128, 202, 0, 0, 192, 63], r.stub.sent[0]);
        assertBytes([147, 17, 90, 0, 128, 2], r.stub.sent[1]);
        assertBytes([147, 16, 90, 0], r.stub.sent[2]);

        assertEquals(1000.0, r.handle.reckonTimeAt(1));
        assertEquals(1017.0, r.handle.reckonTimeAt(2));
        assertEquals(1033.0, r.handle.reckonTimeAt(3));
    }

    public function testHandleReliableStampedRenderOnly() {
        var clock = new StubClock();
        clock.lastServerTimeValue = 500;
        clock.smoothedRttValue = 80;
        var r = makeHandle(clock, { stampRender: true, stampReckon: false, renderDelay: 50 });
        var input: MoveInput = cast r.handle.data;

        clock.serverNowValue = 1000;
        input.vx = 1.5;
        r.handle.send();     // stamp = 1000-90 = 910
        clock.serverNowValue = 1050;
        input.vx = 2;
        r.handle.send();     // Δ = 50

        assertBytes([147, 205, 142, 3, 128, 202, 0, 0, 192, 63], r.stub.sent[0]);
        assertBytes([147, 50, 128, 2], r.stub.sent[1]);
        assertEquals(0.0, r.handle.reckonTimeAt(1)); // reckon ring off
    }

    public function testHandleUnstampedBeforeSync() {
        var clock = new StubClock();
        clock.serverNowValue = 1234;
        clock.lastServerTimeValue = 0; // NOT synced
        clock.smoothedRttValue = 80;
        var r = makeHandle(clock, { stampRender: true, stampReckon: true });
        var input: MoveInput = cast r.handle.data;

        input.vx = 1;
        r.handle.send();
        assertBytes([147, 0, 0, 0, 128, 1], r.stub.sent[0]);
    }

    public function testHandleAllowRewindGate() {
        var clock = new StubClock();
        clock.lastServerTimeValue = 500;
        var r = makeHandle(clock, { stampRender: false, stampReckon: true, allowRewind: (d) -> (d : MoveInput).jump == true });
        var input: MoveInput = cast r.handle.data;

        clock.serverNowValue = 1000;
        input.vx = 1; input.jump = false;
        r.handle.send();                       // unstamped
        clock.serverNowValue = 1100;
        input.jump = true;
        r.handle.send();                       // stamped, Δ=1100
        clock.serverNowValue = 1200;
        input.jump = false;
        r.handle.send();                       // unstamped (baseline holds)
        clock.serverNowValue = 1300;
        input.jump = true;
        r.handle.send();                       // stamped, Δ=200

        // NB: the JS fixture is [19, 128, 1, 130, 0] — its setter-based dirty
        // tracking re-emits `jump = false` (assigned to its default). This
        // port diffs values, so the redundant field is omitted; the server
        // decodes both to identical state (see InputEncoder class doc).
        assertBytes([19, 128, 1], r.stub.sent[0]);
        assertBytes([147, 205, 76, 4, 130, 1], r.stub.sent[1]);
        assertBytes([19, 130, 0], r.stub.sent[2]);
        assertBytes([147, 204, 200, 130, 1], r.stub.sent[3]);
    }

    public function testHandleUnreliable() {
        var clock = new StubClock();
        clock.lastServerTimeValue = 500;
        var r = makeHandle(clock, "unreliable", { stampRender: false, stampReckon: true });
        var input: MoveInput = cast r.handle.data;

        input.vx = 1.5;
        assertEquals(1, r.handle.send());
        input.vx = 2.5;
        assertEquals(2, r.handle.send());
        assertEquals(2, r.handle.sentCount);

        // [20][baseSeq][len][slot]… — unreliable is never stamped
        assertBytes([20, 1, 6, 128, 202, 0, 0, 192, 63], r.stub.sent[0]);
        assertBytes([20, 1, 6, 128, 202, 0, 0, 192, 63, 6, 128, 202, 0, 0, 32, 64], r.stub.sent[1]);
    }

    public function testHandleAckRtt() {
        var NOW: Float = 0;
        var originalNow = RoomClock.getNow;
        RoomClock.getNow = () -> NOW;

        try {
            var r = makeHandle(new StubClock());
            var input: MoveInput = cast r.handle.data;

            NOW = 1000; input.vx = 1; r.handle.send();
            NOW = 1016; input.vx = 2; r.handle.send();
            NOW = 1033; input.vx = 3; r.handle.send();

            NOW = 1080;
            assertEquals(80.0, @:privateAccess r.handle.ackInput(1));
            assertEquals(-1.0, @:privateAccess r.handle.ackInput(1)); // stale
            NOW = 1120;
            assertEquals(87.0, @:privateAccess r.handle.ackInput(3)); // skips 2
            assertEquals(3, r.handle.lastProcessed);
            assertEquals(0, r.handle.pendingCount);

            // replay ring: pending inputs are readable until acked
            NOW = 1200; input.vx = 4; r.handle.send();      // seq 4
            var buffered: MoveInput = cast r.handle.at(4);
            assertEquals(4.0, buffered.vx);
            assertEquals(null, r.handle.at(3));             // acked → gone

            // reset: epoch++, fresh counters, next send = full snapshot
            var epochBefore = r.handle.epoch;
            r.handle.reset();
            assertEquals(epochBefore + 1, r.handle.epoch);
            assertEquals(0, r.handle.sentCount);
            NOW = 1300; input.vx = 5;
            assertEquals(1, r.handle.send());
            assertBytes([19, 128, 5, 129, 0, 130, 0, 131, 0], r.stub.sent[r.stub.sent.length - 1]);
            NOW = 1360;
            assertEquals(60.0, @:privateAccess r.handle.ackInput(1));
        } catch (e: Dynamic) {
            RoomClock.getNow = originalNow;
            throw e;
        }
        RoomClock.getNow = originalNow;
    }

    public function testRoomClockSamples() {
        var NOW: Float = 0;
        var originalNow = RoomClock.getNow;
        RoomClock.getNow = () -> NOW;

        try {
            var clock = new RoomClock();
            clock.setPatchInterval(50);

            // (tNow, sNow, rtt) → (offset, rtt, smoothedRtt, jitter, lastServerTime)
            var script: Array<Array<Float>> = [
                [1000, 500, -1,   -500, 0, 0, 0, 500],
                [1050, 550, 80,   -496, 80, 80, 0, 550],
                [1100, 600, 84,   -492.20000000000005, 84, 80.4, 0, 600],
                [1155, 655, 90,   -488.4800000000001, 90, 81.36000000000001, 0.3125, 655],
                [1205, 705, 76,   -485.83200000000005, 76, 80.82400000000001, 0.29296875, 705],
                [1305, 805, 82,   -483.14880000000005, 82, 80.94160000000002, 0.274658203125, 805],
                [1655, 1155, 78,  -480.93392000000006, 78, 80.64744000000002, 0.274658203125, 1155],
                [1705, 1205, 400, -480.93392000000006, 78, 80.64744000000002, 0.2574920654296875, 1205],
                [1755, 1255, 74,  -479.1405280000001, 74, 79.98269600000002, 0.24139881134033203, 1255],
            ];
            for (row in script) {
                NOW = row[0];
                clock.sample(row[1], row[2]);
                assertEquals(row[3], @:privateAccess clock._clockOffset);
                assertEquals(row[4], clock.rtt());
                assertEquals(row[5], clock.smoothedRtt());
                assertEquals(row[6], clock.jitter());
                assertEquals(row[7], clock.lastServerTime());
            }

            NOW = 1800;
            assertEquals(1320.8594719999999, clock.serverNow());

            // renderNow — 1e-6 tolerance (exp() ULP variance across libms)
            NOW = 1800;
            var r1 = clock.renderNow();
            NOW = 1816;
            var r2 = clock.renderNow();
            NOW = 1816.2;
            var r3 = clock.renderNow();     // same frame → unchanged
            assertTrue(Math.abs(r1 - 1320.8594719999999) < 1e-6);
            assertTrue(Math.abs(r2 - 1336.8594719999999) < 1e-6);
            assertEquals(r2, r3);

            // reset clears estimates; patchInterval is config and survives
            clock.reset();
            assertEquals(0.0, clock.smoothedRtt());
            assertEquals(0.0, clock.lastServerTime());
            assertEquals(50.0, clock.patchInterval());
        } catch (e: Dynamic) {
            RoomClock.getNow = originalNow;
            throw e;
        }
        RoomClock.getNow = originalNow;
    }

    public function testRoomClockGateWarmup() {
        var NOW: Float = 0;
        var originalNow = RoomClock.getNow;
        RoomClock.getNow = () -> NOW;

        try {
            var clock = new RoomClock();
            clock.setPatchInterval(50);
            var tNow: Float = 1000;
            var expected = [
                5 => [-341.855, 116.29],
                10 => [-332.85995895, 134.28008210000002],
                15 => [-331.7339771603856, 136.53204567922904],
                20 => [-326.88359617343616, 146.23280765312796],
                25 => [-328.20499470445236, 143.59001059109553],
                30 => [-324.79976732303214, 150.40046535393603],
                35 => [-331.6290303784904, 146.0509707868457],
            ];
            for (i in 1...36) {
                tNow += 50;
                NOW = tNow;
                var rtt = (i % 2 == 0) ? 200 : 100;
                clock.sample(tNow - 400, rtt);
                if (expected.exists(i)) {
                    assertEquals(expected.get(i)[0], @:privateAccess clock._clockOffset);
                    assertEquals(expected.get(i)[1], clock.smoothedRtt());
                }
            }
        } catch (e: Dynamic) {
            RoomClock.getNow = originalNow;
            throw e;
        }
        RoomClock.getNow = originalNow;
    }

    public function testRoomInputOptionsAndTimedRouting() {
        // JOIN_ROOM fixture with INPUT_REFLECTION + INPUT_OPTIONS sections
        // (flags FIXED|PATCH|SUB, tickRate 20, patchRate 50, subSteps 2) —
        // from PORTING/generate-phase0-fixtures.cts.
        var room = new Room<P0State>("phase0", P0State);
        room.roomId = "phase0";
        var stub = new StubConnection();
        room.connection = stub;

        @:privateAccess room.onMessageCallback(getBytes([10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2]));

        assertEquals(50.0, room.clock.patchInterval());

        var handle = room.input({ type: MoveInput });
        assertEquals(20, handle.tickRate);
        assertEquals(50, handle.patchRate);
        assertEquals(2, handle.subSteps);
        assertEquals(0.05, handle.stepSeconds);
        assertEquals(0.025, handle.subStepSeconds);
        assertTrue(handle.replayBufferSize >= 64);

        // same handle on later calls
        assertTrue(handle == room.input());

        // TIMED heartbeat patch [15|0x80][u32 sNow=750][u32 inputSeq=0]
        @:privateAccess room.onMessageCallback(getBytes([143, 238, 2, 0, 0, 0, 0, 0, 0]));
        assertEquals(750.0, room.clock.lastServerTime());
    }

    /**
     * `room.input({ type: T })` hands back an `InputHandle<T>`, so the central
     * idiom is a real field access. It used to be typed `Schema`, which made
     * `input.data.vx` a compile error and put a bare `cast` in every consumer.
     *
     * The compile-time half of this test is the test: `jump` is declared `Bool`
     * on MoveInput, so neither line below type-checks against a `Schema`.
     */
    public function testInputHandleIsTypedByItsSchema() {
        var room = new Room<P0State>("phase0", P0State);
        room.connection = new StubConnection();

        var input = room.input({ type: MoveInput });
        input.data.vx = 3;
        input.data.jump = true;
        assertEquals(3, (input.data.vx : Int));
        assertTrue(input.data.jump);

        // at() carries the same type through the replay ring
        var seq = input.send();
        var past = input.at(seq);
        assertEquals(3, (past.vx : Int));
        assertTrue(past.jump);
    }

    /**
     * First call wins, so a later call naming a different type would hand back
     * a handle whose `data` is not what its type says — nothing downstream can
     * notice, so it has to say so here.
     */
    public function testRoomInputWarnsOnALaterDifferentType() {
        var traced: Array<String> = [];
        var savedTrace = haxe.Log.trace;
        haxe.Log.trace = (value: Dynamic, ?_infos: haxe.PosInfos) -> traced.push(Std.string(value));

        var room = new Room<P0State>("phase0", P0State);
        room.connection = new StubConnection();
        var first = room.input({ type: MoveInput });

        // same type, and the no-args fetch: both silent
        room.input({ type: MoveInput });
        room.input();
        assertEquals(0, traced.length);

        var second = room.input({ type: schema.predict.AccelInput });
        haxe.Log.trace = savedTrace;

        assertTrue(first == cast second);
        assertEquals(1, traced.length);
        assertTrue(traced[0].indexOf("already built") > -1);
    }

    public function testRoomInputUnreliableModeIsRejected() {
        // No datagram transport in this SDK yet — mode "unreliable" must fail
        // loudly at construction rather than silently ride the reliable channel.
        var room = new Room<P0State>("phase0", P0State);
        var threw = false;
        try room.input({ type: MoveInput, mode: "unreliable" }) catch (e: Dynamic) threw = true;
        assertTrue(threw);
    }
}
