import haxe.io.Bytes;
import haxe.io.BytesOutput;

import io.colyseus.Room;
import io.colyseus.Connection;

import schema.phase0.P0State;

/**
 * Stub connection: captures outgoing frames, always reports open, never
 * touches the (dangling, never-connected) underlying socket.
 */
class StubConnection extends Connection {
    public var sent: Array<Bytes> = [];

    public function new() {
        super("ws://127.0.0.1:9");
    }

    override public function send(data: Bytes) {
        this.sent.push(data);
    }

    override function get__isOpen(): Bool {
        return true;
    }
}

/**
 * 0.18 wire-compat (Phase 0) — room-level protocol frames.
 *
 * Fixtures below generated by colyseus-0.18
 * PORTING/generate-phase0-fixtures.cts (self-verified against the JS
 * packages/sdk Room). See PORTING/sdk-coverage-plan-0.18.md.
 */
class RoomProtocolTestCase extends haxe.unit.TestCase {

    private function getBytes(arr: Array<Int>): Bytes {
        var bytes = Bytes.alloc(arr.length);
        var i: Int = 0;
        for (byte in arr) { bytes.set(i++, byte); }
        return bytes;
    }

    private function makeRoom(): { room: Room<P0State>, stub: StubConnection } {
        var room = new Room<P0State>("phase0", P0State);
        room.roomId = "phase0";
        var stub = new StubConnection();
        room.connection = stub;
        return { room: room, stub: stub };
    }

    private function feed(room: Room<P0State>, frame: Array<Int>) {
        @:privateAccess room.onMessageCallback(getBytes(frame));
    }

    public function testJoinRoomFullHandshake() {
        var r = makeRoom();

        var joins = 0;
        r.room.onJoin += () -> joins++;

        // JOIN_ROOM with length-prefixed state reflection + INPUT_REFLECTION
        // and INPUT_OPTIONS tagged sections (room uses defineInput())
        feed(r.room, [10, 6, 116, 111, 107, 49, 50, 51, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114, 1, 47, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 161, 120, 129, 166, 110, 117, 109, 98, 101, 114, 255, 5, 128, 161, 121, 129, 166, 110, 117, 109, 98, 101, 114, 2, 4, 14, 20, 50, 2]);

        assertEquals(1, joins);
        assertEquals("phase0:tok123", r.room.reconnectionToken);
        // acknowledged with a single JOIN_ROOM byte
        assertEquals(1, r.stub.sent.length);
        assertEquals(1, r.stub.sent[0].length);
        assertEquals(10, r.stub.sent[0].get(0));

        // full state
        feed(r.room, [14, 128, 165, 104, 101, 108, 108, 111, 129, 42]);
        assertEquals("hello", r.room.state.msg);
        assertEquals(42., r.room.state.n);

        // TIMED-modified patch (143 = 15 | 0x80): the 8-byte
        // [uint32 sNow][uint32 inputSeq] prefix must be consumed
        feed(r.room, [143, 64, 226, 1, 0, 7, 0, 0, 0, 129, 43]);
        assertEquals(43., r.room.state.n);
    }

    public function testJoinRoomPlainAndReconnect() {
        var r = makeRoom();

        var joins = 0;
        var reconnects = 0;
        r.room.onJoin += () -> joins++;
        r.room.onReconnect += () -> reconnects++;

        // plain room: state reflection only, no trailing sections
        feed(r.room, [10, 4, 116, 111, 107, 65, 6, 115, 99, 104, 101, 109, 97, 49, 128, 1, 255, 1, 128, 0, 2, 255, 2, 128, 0, 130, 3, 255, 3, 128, 0, 4, 128, 1, 5, 255, 4, 128, 163, 109, 115, 103, 129, 166, 115, 116, 114, 105, 110, 103, 255, 5, 128, 161, 110, 129, 166, 110, 117, 109, 98, 101, 114]);
        assertEquals(1, joins);
        assertEquals(0, reconnects);

        // reconnect JOIN: zero-length state reflection (serializer has state)
        feed(r.room, [10, 4, 116, 111, 107, 66, 6, 115, 99, 104, 101, 109, 97, 0]);
        assertEquals(1, joins);
        assertEquals(1, reconnects);
        assertEquals("phase0:tokB", r.room.reconnectionToken);
    }

    public function testRequestFrameEncoding() {
        var r = makeRoom();

        r.room.request("move", 7, (_, _) -> {});

        assertEquals(1, r.stub.sent.length);
        // [21][requestId 0]['move' fixstr][msgpack 7]
        var expected = [21, 0, 164, 109, 111, 118, 101, 7];
        assertEquals(expected.length, r.stub.sent[0].length);
        for (i in 0...expected.length) {
            assertEquals(expected[i], r.stub.sent[0].get(i));
        }
    }

    public function testRequestResponseOutcomes() {
        var r = makeRoom();

        var responses: Array<Dynamic> = [];
        var errors: Array<Dynamic> = [];
        var reply = (response, error) -> { responses.push(response); errors.push(error); };

        // ids mint from 0 in order
        r.room.request("a", null, reply);
        r.room.request("b", null, reply);
        r.room.request("c", null, reply);
        r.room.request("d", null, reply);

        feed(r.room, [22, 0, 0, 42]);                                       // OK, payload 42
        feed(r.room, [22, 1, 0]);                                           // OK, no payload
        feed(r.room, [22, 2, 1, 164, 110, 111, 112, 101]);                  // REJECTED, "nope"
        feed(r.room, [22, 3, 2, 222, 0, 2, 164, 110, 97, 109, 101, 165, 69, 114, 114, 111, 114, 167, 109, 101, 115, 115, 97, 103, 101, 164, 98, 111, 111, 109]); // ERROR, {name,message}
        feed(r.room, [22, 205, 231, 3, 0, 1]);                              // unknown id 999 — ignored

        assertEquals(4, responses.length);
        assertEquals(42., responses[0]);
        assertEquals(null, errors[0]);
        assertEquals(null, responses[1]);
        assertEquals(null, errors[1]); // OK with no payload: response null, no error
        assertEquals("nope", errors[2]);
        assertEquals("Error", errors[3].name);
        assertEquals("boom", errors[3].message);
    }

    public function testRejectAllPendingOnClose() {
        var r = makeRoom();

        var errors: Array<Dynamic> = [];
        r.room.request("a", null, (_, error) -> errors.push(error));
        r.room.request("b", null, (_, error) -> errors.push(error));

        @:privateAccess r.room.rejectAllPendingRequests("connection closed before a response was received.");

        assertEquals(2, errors.length);
        assertEquals("connection closed before a response was received.", errors[0]);

        // a late response for a rejected id is ignored
        feed(r.room, [22, 0, 0, 42]);
        assertEquals(2, errors.length);
    }

}
