import haxe.io.Bytes;
import io.colyseus.serializer.schema.Callbacks.SchemaCallbacks;
import io.colyseus.serializer.schema.Decoder;
import schema.nestedmap.NestedMap;
import schema.nestedmap.NestedMapObservables;

class SchemaListenMacroTestCase extends haxe.unit.TestCase {
	public function testNestedMapListenersWriteIntoTheirOwnRow() {
		var state = new NestedMap();
		var decoder = new Decoder(state);
		var obs = new NestedMapObservables();
		obs.listen(new SchemaCallbacks<NestedMap>(decoder), state);

		// generated by schema-5.0: rows {a: {x: 1, y: 2}, b: {z: 3}}
		decoder.decode(getBytes([128, 1, 255, 1, 128, 2, 255, 2, 128, 0, 161, 97, 3, 128, 1, 161, 98, 7, 255, 3, 128, 4, 255, 4, 128, 0, 161, 120, 5, 128, 1, 161, 121, 6, 255, 5, 128, 1, 255, 6, 128, 2, 255, 7, 128, 8, 255, 8, 128, 0, 161, 122, 9, 255, 9, 128, 3]));
		assertEquals("a:{x=1,y=2} b:{z=3}", dump(obs));

		// rows.set("c", {w: 4}); rows["a"].cells.set("q", 5); rows["b"].cells.delete("z")
		decoder.decode(getBytes([255, 2, 128, 2, 161, 99, 10, 255, 10, 128, 11, 255, 11, 128, 0, 161, 119, 12, 255, 12, 128, 4, 255, 4, 128, 2, 161, 113, 13, 255, 13, 128, 5, 255, 8, 64, 0]));
		assertEquals("a:{q=5,x=1,y=2} b:{} c:{w=4}", dump(obs));

		// rows.delete("b"); rows["c"].cells["w"].value = 40
		decoder.decode(getBytes([255, 2, 64, 1, 255, 12, 128, 40]));
		assertEquals("a:{q=5,x=1,y=2} c:{w=40}", dump(obs));
	}

	static function dump(obs:NestedMapObservables):String {
		var rows = obs.child.value.rows;
		return [for (rowKey in sorted(rows.keys())) {
			var cells = rows.get(rowKey).cells;
			rowKey + ":{" + [for (cellKey in sorted(cells.keys())) cellKey + "=" + cells.get(cellKey).value.value].join(",") + "}";
		}].join(" ");
	}

	static function sorted(keys:Iterator<String>) {
		var arr = [for (k in keys) k];
		arr.sort(Reflect.compare);
		return arr;
	}

	function getBytes(arr:Array<Int>) {
		var bytes = Bytes.alloc(arr.length);
		for (i in 0...arr.length) bytes.set(i, arr[i]);
		return bytes;
	}
}
