import haxe.io.Bytes;
import io.colyseus.serializer.schema.Callbacks.SchemaCallbacks;
import io.colyseus.serializer.schema.Decoder;
import schema.splitmodules.SplitRoot;
import tink.core.Callback.CallbackLink;
import tink.state.*;

class SchemaTypeUtilsTestCase extends haxe.unit.TestCase {
	public function testNestedMapWithChildInSameModule() {
		assertTrue(NestedMapCheck.resolvesChildMap());
		assertTrue(new schema.nestedmap.NestedMapObservables() != null);
	}

	public function testMapElementsResolvedFromOutsideTheirPackage() {
		var state = new SplitRoot();
		var decoder = new Decoder(state);
		var obs = new SplitRootObservables();
		obs.listen(new SchemaCallbacks<SplitRoot>(decoder), state);

		// generated by schema-5.0: rows {a: 1, b: 2}, flags {ready: true, muted: false}
		decoder.decode(getBytes([128, 1, 129, 4, 255, 1, 128, 0, 161, 97, 2, 128, 1, 161, 98, 3, 255, 2, 128, 1, 255, 3, 128, 2, 255, 4, 128, 0, 165, 114, 101, 97, 100, 121, 1, 128, 1, 165, 109, 117, 116, 101, 100, 0]));

		assertEquals(1, obs.rows.get("a").value.value);
		assertEquals(2, obs.rows.get("b").value.value);
		assertTrue(obs.flags.get("ready"));
		assertFalse(obs.flags.get("muted"));
	}

	function getBytes(arr:Array<Int>) {
		var bytes = Bytes.alloc(arr.length);
		for (i in 0...arr.length) bytes.set(i, arr[i]);
		return bytes;
	}
}

// SplitRow isn't imported here, so it can't be resolved by name from this package
@:build(io.colyseus.tools.ObservableSchemaMacro.build(SplitRoot))
private class SplitRootObservables {
	public function listen(callbacks:SchemaCallbacks<SplitRoot>, state:SplitRoot):CallbackLink
		return io.colyseus.tools.SchemaListenMacro.listenRef(callbacks, state);
}
