package io.colyseus;

import haxe.io.Bytes;
import haxe.io.BytesOutput;
import io.colyseus.Connection;
import io.colyseus.Protocol;
import io.colyseus.RoomClock;
import io.colyseus.serializer.schema.Schema;
import io.colyseus.serializer.schema.InputEncoder;
import io.colyseus.serializer.schema.encoding.Encode;

/** Options accepted by `Room.input()`. `T` is inferred from `type`. */
typedef InputOptions<T> = {
	/**
	 * Schema constructor for the input. REQUIRED on this SDK: Haxe cannot
	 * synthesize a class from the server's input reflection at runtime, so
	 * pass the class generated by schema-codegen (or hand-written to match
	 * the server's `defineInput()` schema).
	 *
	 * This is also what types the handle: pass `PaddleInput` and `data` /
	 * `at()` come back as `PaddleInput`, so `input.data.dx` is a real field
	 * access rather than a cast.
	 */
	var type: Class<T>;
	/** "reliable" (default). "unreliable" is rejected for now — it needs a
	 *  WebTransport datagram channel, which this SDK does not have. */
	@:optional var mode: String;
	/** Unreliable-mode redundancy ring size (default 3). */
	@:optional var historySize: Int;
	/** Interpolation buffer (ms) — how far in the past remote entities render. */
	@:optional var renderDelay: Float;
	/** Per-send gate: stamp only inputs the server may rewind to. */
	@:optional var allowRewind: Dynamic -> Bool;
};

/**
 * Per-room input handle returned by `Room.input()`. Mutate `data`, then call
 * `send()` to delta-encode and transmit. Port of the JS SDK's
 * `input/InputHandle.ts` — see PORTING/sdk-ports-input-layer.md for the wire
 * contract (frame layout, stamp deltas, ack/RTT, replay ring).
 *
 * `T` is the input schema, inferred from `room.input({ type: ... })`, so `data`
 * and `at()` are typed and `input.data.dx` is a real field access. Anything
 * that only DRIVES a handle (the prediction layer's `input` option) takes
 * `InputHandle<Dynamic>`, which every `InputHandle<T>` satisfies.
 */
class InputHandle<T:Schema> {
	/** Mutable schema instance — mutate, then call `send()`. */
	public var data(default, null): T;

	public var mode(get, never): String;
	function get_mode() return this._encoder.mode;

	/** Server-advertised fixed step rate (Hz); null when not advertised. */
	public var tickRate(default, null): Null<Int>;
	/** Server-advertised state-patch interval (ms) = the reconcile cadence. */
	public var patchRate(default, null): Null<Int>;
	/** Physics sub-steps per input tick (1 when the server doesn't sub-step). */
	public var subSteps(default, null): Int = 1;

	/** The fixed step in seconds (`1/tickRate`); null when no rate advertised. */
	public var stepSeconds(get, never): Null<Float>;
	function get_stepSeconds() return tickRate != null ? 1.0 / tickRate : null;
	/** The fixed step in milliseconds. */
	public var stepMs(get, never): Null<Float>;
	function get_stepMs() return tickRate != null ? 1000.0 / tickRate : null;
	/** The physics sub-step in seconds (`stepSeconds / subSteps`). */
	public var subStepSeconds(get, never): Null<Float>;
	function get_subStepSeconds() return tickRate != null ? (1.0 / tickRate) / subSteps : null;
	/** The physics sub-step in milliseconds. */
	public var subStepMs(get, never): Null<Float>;
	function get_subStepMs() return tickRate != null ? (1000.0 / tickRate) / subSteps : null;

	/** Last input the server acked PROCESSING into its state. */
	public var lastProcessed(default, null): Int = 0;
	/** Reliable inputs transmitted (the seq the server will ack). */
	public var sentCount(default, null): Int = 0;
	/** Sent but not yet acked (`sentCount − lastProcessed`). */
	public var pendingCount(get, never): Int;

	/**
	 * How far in the PAST this client draws remote entities, in ms. A
	 * lag-compensating server rewinds its targets by this much plus half the RTT,
	 * so it reads the world at the instant you actually saw — get it wrong and
	 * every shot misses by exactly the difference. `predict.reconciler()`
	 * binds it from the lerp delay you already attached with; set it yourself
	 * only to override.
	 */
	public function renderDelay(): Float {
		return this._renderDelay;
	}

	public function setRenderDelay(ms: Float): Void {
		this._renderDelay = (ms > 0) ? ms : 0;
	}
	function get_pendingCount() return sentCount - lastProcessed;
	/** Capacity (in seqs) of the replay ring backing `at()`. */
	public var replayBufferSize(default, null): Int;
	/** Monotonic reset counter — rollback controllers poll it and self-reset. */
	public var epoch(default, null): Int = 0;

	private var _encoder: InputEncoder;
	private var _getConnection: Void -> Connection;
	private var _getClock: Void -> RoomClock;

	private var _stampRender: Bool;
	private var _stampReckon: Bool;
	private var _renderDelay: Float;
	private var _allowRewind: Dynamic -> Bool;
	private var _lastStamp: Float = 0;       // delta-coded stamp baseline
	private var _pendingReckon: Float = 0;

	private var _sendTimes: Array<Float>;              // seq % size → send time
	private var _inputBuffer: Array<T> = null;    // replay ring (lazily allocated)
	private var _reckonTimes: Array<Float> = null;     // per-seq reckon stamps
	private var _sendListeners: Array<Int -> Void> = null;
	private static var _warnedBufferOverflow = false;

	private static inline var BUFFER_FLOOR = 64;
	private static inline var BUFFER_RTT_BUDGET_MS = 1000.0;
	private static inline var BUFFER_HEADROOM = 1.5;

	@:allow(io.colyseus.Room)
	private function new(
		data: T,
		encoder: InputEncoder,
		opts: { stampRender: Bool, stampReckon: Bool, ?renderDelay: Float, ?allowRewind: Dynamic -> Bool, ?tickRate: Int, ?patchRate: Int, ?subSteps: Int },
		getConnection: Void -> Connection,
		getClock: Void -> RoomClock
	) {
		this.data = data;
		this._encoder = encoder;
		this._getConnection = getConnection;
		this._getClock = getClock;
		this._stampRender = opts.stampRender;
		this._stampReckon = opts.stampReckon;
		this._renderDelay = (opts.renderDelay != null) ? opts.renderDelay : 0;
		this._allowRewind = opts.allowRewind;
		this.tickRate = opts.tickRate;
		this.patchRate = opts.patchRate;
		this.subSteps = (opts.subSteps != null && opts.subSteps > 1) ? opts.subSteps : 1;

		// replay ring sized to worst-case in-flight = (RTT budget + patch interval) × input rate
		var stepMs = (this.tickRate != null) ? 1000.0 / this.tickRate : (1000.0 / 60);
		var window = BUFFER_RTT_BUDGET_MS + ((this.patchRate != null) ? this.patchRate : 0);
		var size = Math.ceil((window / stepMs) * BUFFER_HEADROOM);
		this.replayBufferSize = (size > BUFFER_FLOOR) ? size : BUFFER_FLOOR;

		this._sendTimes = [for (_ in 0...this.replayBufferSize) 0.0];
	}

	/**
	 * Encode the staged input and send it. Always transmits one input when
	 * the connection is open — a body-less frame on a no-change tick (the
	 * server holds last values but still bumps its consumed count). Returns
	 * the seq assigned to this input, or `0` when nothing was sent
	 * (connection closed) — seqs are 1-based.
	 */
	public function send(): Int {
		var conn = this._getConnection();
		if (conn == null || !conn._isOpen) { return 0; }

		var body = this._encoder.encode();
		var reliable = (this._encoder.mode == "reliable");

		var wantStamp = (this._stampReckon || this._stampRender) && reliable
			&& (this._allowRewind == null || this._allowRewind(this.data));
		var both = this._stampReckon && this._stampRender;

		var out = new BytesOutput();
		out.writeByte((reliable ? Protocol.ROOM_INPUT_RELIABLE : Protocol.ROOM_INPUT_UNRELIABLE)
			| (wantStamp ? ProtocolModifier.TIMED : 0));

		if (wantStamp) {
			var clock = this._getClock();
			var synced = clock != null && clock.lastServerTime() > 0;
			var rk: Float = synced ? Math.max(0, Math.fround(clock.serverNow())) : 0;
			this._pendingReckon = rk;
			var renderDelta: Float = synced
				? Math.min(0xffff, Math.max(0, Math.fround(this._renderDelay + clock.smoothedRtt() / 2)))
				: 0;
			// the mode's single u32 timeline, delta-coded vs the baseline;
			// BOTH mode trails the absolute u16 renderDelta
			var stamp = this._stampReckon ? rk : ((rk > renderDelta) ? rk - renderDelta : 0);
			Encode.number(out, stamp - this._lastStamp);
			this._lastStamp = stamp;
			if (both) { Encode.uint16(out, Std.int(renderDelta)); }
		} else {
			this._pendingReckon = 0;
		}

		out.writeBytes(body, 0, body.length);
		conn.send(out.getBytes()); // WS-only transport: unreliable falls back to the reliable channel

		var seq: Int;
		if (reliable) {
			seq = ++this.sentCount; // implicit count seq — mirrors the server's consumed counter
		} else {
			seq = this.sentCount = this._encoder.seq; // adopt the framework seq (stamped on the wire)
		}
		this.recordSent(seq);
		return seq;
	}

	/**
	 * Subscribe to sends: `listener(seq)` fires synchronously at the end of
	 * each `send()` (replay ring + reckon instant already recorded). Returns
	 * an unsubscribe function.
	 */
	public function onSend(listener: Int -> Void): Void -> Void {
		if (this._sendListeners == null) { this._sendListeners = []; }
		this._sendListeners.push(listener);
		return () -> this._sendListeners.remove(listener);
	}

	/**
	 * Reset encoder + round-trip state (the SDK calls this on reconnect):
	 * next send emits a full snapshot; the stamp baseline re-zeroes; pending
	 * count restarts; `epoch` increments so observing controllers self-reset.
	 */
	public function reset() {
		this._encoder.reset();
		this.sentCount = this.lastProcessed = this._encoder.seq;
		this._lastStamp = 0;
		for (i in 0...this._sendTimes.length) { this._sendTimes[i] = 0; }
		this.epoch++;
	}

	/**
	 * The buffered snapshot of reliable input `seq`, for reconciliation
	 * replay. `null` if already acked, never sent, or aged out. The instance
	 * is REUSED — read synchronously, don't retain.
	 */
	public function at(seq: Int): T {
		if (this._inputBuffer == null) { return null; }
		if (seq <= this.lastProcessed || seq > this.sentCount) { return null; }
		if (this.sentCount - seq >= this.replayBufferSize) {
			if (!_warnedBufferOverflow) {
				_warnedBufferOverflow = true;
				trace("colyseus: input replay buffer (" + this.replayBufferSize + ") overflowed — reconciliation may drift.");
			}
			return null;
		}
		return this._inputBuffer[seq % this.replayBufferSize];
	}

	/**
	 * The reckon instant (server-clock ms) stamped onto reliable input `seq`;
	 * `0` when reckon stamping is off or `seq` is outside the valid window.
	 */
	public function reckonTimeAt(seq: Int): Float {
		if (this._reckonTimes == null) { return 0; }
		if (seq <= this.lastProcessed || seq > this.sentCount) { return 0; }
		if (this.sentCount - seq >= this.replayBufferSize) { return 0; }
		return this._reckonTimes[seq % this.replayBufferSize];
	}

	/**
	 * Feed the server's last-PROCESSED input seq (decoded from the TIMED
	 * prefix). Advances `lastProcessed` and returns the RTT sample for that
	 * ack, or `-1` when unknown (stale seq / aged out / pre-reset send).
	 */
	@:allow(io.colyseus.Room)
	private function ackInput(seq: Int): Float {
		if (seq <= this.lastProcessed) { return -1; }
		var aged = this.sentCount - seq >= this.replayBufferSize;
		this.lastProcessed = seq;
		if (aged) { return -1; }
		var sentAt = this._sendTimes[seq % this.replayBufferSize];
		return (sentAt > 0) ? RoomClock.getNow() - sentAt : -1;
	}

	/** Snapshot the just-sent input + its send time (and reckon stamp) by seq. */
	private function recordSent(seq: Int) {
		if (this._inputBuffer == null) {
			var cls = Type.getClass(this.data);
			this._inputBuffer = [for (_ in 0...this.replayBufferSize) (cast Type.createInstance(cls, []) : T)];
		}
		this._encoder.copyInto(this._inputBuffer[seq % this.replayBufferSize]);
		this._sendTimes[seq % this.replayBufferSize] = RoomClock.getNow();
		if (this._stampReckon) {
			if (this._reckonTimes == null) {
				this._reckonTimes = [for (_ in 0...this.replayBufferSize) 0.0];
			}
			this._reckonTimes[seq % this.replayBufferSize] = this._pendingReckon;
		}
		if (this._sendListeners != null) {
			for (listener in this._sendListeners.copy()) { listener(seq); }
		}
	}
}
